export const QUERY_KEY = {
  // Admin
  GET_ME: 'GET_ME',
  GET_USER: 'GET_USER',
  GET_USERS: 'GET_USERS',
  GET_AGENT: 'GET_AGENT',
  GET_AGENTS: 'GET_AGENTS',
  GET_COMPANY: 'GET_COMPANY',
  GET_COMPANIES: 'GET_COMPANIES',
  GET_ACCOUNTS: 'GET_ACCOUNT',

  GET_ROLES: 'GET_ROLES',
  GET_ROLE_DETAIL: 'GET_ROLE_DETAIL',
  GET_PERMISSIONS: 'GET_PERMISSIONS',

  GET_LICENSES: 'GET_LICENSES',
  GET_LICENSES_MOBILE_ID: 'GET_LICENSES_MOBILE_ID',
  GET_DOCUMENTS: 'GET_DOCUMENTS',
  GET_DETAIL_DOCUMENT: 'GET_DETAIL_DOCUMENT',
  GET_MY_PROFILE: 'GET_MY_PROFILE',
  GET_SUPPORTS: 'GET_SUPPORTS',
  GET_LOGS: 'GET_LOGS',
  GET_CONVERSION_METRICS: 'GET_CONVERSION_METRICS',
  GET_SUPPORT: 'GET_SUPPORT',
  GET_INFINITE_AGENTS: 'GET_INFINITE_AGENTS',
  GET_INFINITE_ROLES: 'GET_INFINITE_ROLES',
  GET_INFINITE_LICENSE: 'GET_INFINITE_LICENSE',
  GET_MY_AGENT: 'GET_MY_AGENT',
  GET_OVERVIEW: 'GET_OVERVIEW',
  GET_REVENUE: 'GET_REVENUE',
  GET_AUTH: 'GET_AUTH',

  GET_ADMIN_EKYC_LOGS: 'GET_ADMIN_EKYC_LOGS',
  GET_ADMIN_EKYC_CUSTOMERS: 'GET_ADMIN_EKYC_CUSTOMERS',
  GET_ADMIN_EKYC_SESSIONS: 'GET_ADMIN_EKYC_SESSIONS',

  GET_MY_COMPANY_PROFILE: 'GET_MY_COMPANY_PROFILE',
  GET_COMPANY_LICENSES: 'GET_COMPANY_LICENSES',
  GET_COMPANY_LICENSES_MOBILE_ID: 'GET_COMPANY_LICENSES_MOBILE_ID',
  GET_COMPANY_DOCUMENT: 'GET_COMPANY_DOCUMENT',
  GET_COMPANY_DOCUMENTS: 'GET_COMPANY_DOCUMENTS',
  GET_COMPANY_LOGS: 'GET_COMPANY_LOGS',
  GET_COMPANY_CONVERSION_METRICS: 'GET_COMPANY_CONVERSION_METRICS',
  GET_COMPANY_SUPPORT: 'GET_COMPANY_SUPPORT',
  GET_COMPANY_SUPPORTS: 'GET_COMPANY_SUPPORTS',
  GET_COMPANY_USERS: 'GET_COMPANY_USERS',
  GET_COMPANY_ROLES: 'GET_COMPANY_ROLES',
  GET_COMPANY_ROLE: 'GET_COMPANY_ROLE',

  GET_PROVIDER_DEVICES: 'GET_PROVIDER_DEVICES',
  GET_PROVIDER_DEVICE_DETAIL: 'GET_PROVIDER_DEVICE_DETAIL',

  GET_PROVIDER_CONTENTS: 'GET_PROVIDER_CONTENTS',
  GET_PROVIDER_CONTENT_DETAIL: 'GET_PROVIDER_CONTENT_DETAIL',

  GET_DEVICES: 'GET_DEVICES',
  GET_DEVICE_DETAIL: 'GET_DEVICE_DETAIL',

  GET_SONGS: 'GET_SONGS',
  GET_SONG_DETAIL: 'GET_SONG_DETAIL',

  GET_PARTNER_LICENSES: 'GET_PARTNER_LICENSES',
  GET_PARTNER_LICENSE_DETAIL: 'GET_PARTNER_LICENSE_DETAIL',

  GET_MERCHANTS: 'GET_MERCHANTS',
  GET_MERCHANT_DETAIL: 'GET_MERCHANT_DETAIL',

  GET_MERCHANT_BRANCHES: 'GET_MERCHANT_BRANCHES',
  GET_MERCHANT_BRANCH_DETAIL: 'GET_MERCHANT_BRANCH_DETAIL',

  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTION_DETAIL: 'GET_TRANSACTION_DETAIL',

  GET_COMPANY_EKYC_LOGS: 'GET_COMPANY_EKYC_LOGS',
  GET_COMPANY_EKYC_CUSTOMERS: 'GET_COMPANY_EKYC_CUSTOMERS',
  GET_COMPANY_EKYC_SESSIONS: 'GET_COMPANY_EKYC_SESSIONS',

  GET_COMPANY_OVERVIEW: 'GET_COMPANY_OVERVIEW',
  GET_COMPANY_REVENUE: 'GET_COMPANY_REVENUE',
  GET_COMPANY_AUTH: 'GET_COMPANY_AUTH',
};
